config/routes.rb
Rails.application.routes.draw do

<<<<<<< HEAD
  resources :tasks
  resources :relatos
  resources :conditionals
  resources :projetos
  resources :locals
  resources :clientes
  resources :reltasks
  resources :users, only: [:new, :create, :update, :destroy] do
=======
  resources :relatos
  resources :conditionals
  resources :tasks
  resources :projetos
  resources :locals
  resources :clientes
  resources :users, only: [:new, :create] do
>>>>>>> ad10758ddfdbf1227205791189757be3232ce289
    member do
      get :activate
    end
  end

  resources :reset_passwords, only: [:new, :create, :update, :edit]

  resources :sessions, only: [:new, :create, :destroy]

  get '/consultor', to: 'users#new', as: :sign_up
get '/cliente', to: 'clientes#new', as: :clienta
<<<<<<< HEAD
get '/projetos/new', to: 'projetos#new', as: :projetopo
=======
get '/projetos', to: 'projetos#index', as: :projete
>>>>>>> ad10758ddfdbf1227205791189757be3232ce289
get '/atividades', to: 'tasks#new', as: :taski
get '/relatorio', to: 'relatos#new', as: :relatoss
get '/condicional', to: 'conditionals#new', as: :condit
get '/local', to: 'locals#new', as: :loca

  get '/log_in', to: 'sessions#new', as: :log_in
  delete '/log_out', to: 'sessions#destroy', as: :log_out

<<<<<<< HEAD
=======
  get '/secret', to: 'pages#index', as: :secret
>>>>>>> ad10758ddfdbf1227205791189757be3232ce289

  root to: 'sessions#new'

end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
belongs_to :page
<<<<<<< HEAD
=======
has_one :local
>>>>>>> ad10758ddfdbf1227205791189757be3232ce289
has_many :projetos
belongs_to :projeto
has_many :relatos
has_many :locals
<<<<<<< HEAD
belongs_to :local
has_many :tasks, :through => :projetos
belongs_to :task
has_many :pages
accepts_nested_attributes_for :locals, allow_destroy: true
=======
has_many :tasks, :through => :projetos
belongs_to :task
has_many :pages
 accepts_nested_attributes_for :local 
>>>>>>> ad10758ddfdbf1227205791189757be3232ce289
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_action :set_cliente, only: [:show, :edit, :update, :destroy]

  # GET /clientes
  # GET /clientes.json
  def index
    @clientes = Cliente.all
  end

  # GET /clientes/1
  # GET /clientes/1.json
  def show
  @cliente = Cliente.find(params[:id])

  end

  # GET /clientes/new
  def new
<<<<<<< HEAD

 @cliente = Cliente.new
 @clientes = Cliente.all
 @local = Local.new
 @locals = Local.all


=======
 @cliente = Cliente.new
  @cliente.build_local
>>>>>>> ad10758ddfdbf1227205791189757be3232ce289
end
  # GET /clientes/1/edit
  def edit
  end

  # POST /clientes
  # POST /clientes.json
  def create
<<<<<<< HEAD

 if params[:commit] == 'Cadastrar' 
=======
>>>>>>> ad10758ddfdbf1227205791189757be3232ce289
    @cliente = Cliente.new(cliente_params)

    respond_to do |format|
      if @cliente.save
<<<<<<< HEAD
        format.html { redirect_to clienta_path, notice: 'Cliente cadastrado com sucesso!' }
=======
        format.html { redirect_to loca_path, notice: 'Cliente cadastrado com sucesso! Por gentileza, Adicioar o Local de Atendimento' }
>>>>>>> ad10758ddfdbf1227205791189757be3232ce289
        format.json { render :show, status: :created, location: @cliente }
      else
        format.html { render :new }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
<<<<<<< HEAD
 elsif params[:commit] == 'Adicionar'

  @local = Local.new(local_params)

    respond_to do |format|
      if @local.save
        format.html { redirect_to clienta_path, notice: 'Local adicionado com sucesso! Agora adicione um novo Projeto!' }
        format.json { render :show, status: :created, location: @local }
      else
        format.html { render :new }
        format.json { render json: @local.errors, status: :unprocessable_entity }
      end
    end
end
=======
>>>>>>> ad10758ddfdbf1227205791189757be3232ce289
  end

  # PATCH/PUT /clientes/1
  # PATCH/PUT /clientes/1.json
  def update
    respond_to do |format|
      if @cliente.update(cliente_params)
        format.html { redirect_to @cliente, notice: 'Cliente was successfully updated.' }
        format.json { render :show, status: :ok, location: @cliente }
      else
        format.html { render :edit }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1
  # DELETE /clientes/1.json
  def destroy
    @cliente.destroy
    respond_to do |format|
      format.html { redirect_to clientes_url, notice: 'Cliente was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cliente
      @cliente = Cliente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cliente_params
<<<<<<< HEAD
      params.require(:cliente).permit(:id, :name, :telefone, :celular, :email, :locals_attributes => [:logra, :cep, :uf, :city, :km, :id, :_destroy])
    end

 def local_params
      params.require(:local).permit(:cliente_id, :logra, :cep, :uf, :city, :km)
=======
      params.require(:cliente).permit(:name, :telefone, :celular, :email, :local_attributes => [:logra, :cep, :uf, :city, :km])
>>>>>>> ad10758ddfdbf1227205791189757be3232ce289
    end

end

app/helpers/clientes_helper.rb
module ClientesHelper
<<<<<<< HEAD

=======
>>>>>>> ad10758ddfdbf1227205791189757be3232ce289
end

app/views/clientes/_form.html.erb
<<<<<<< HEAD
<%= javascript_include_tag 'jquery.dataTables.min' %>

<!-- Inicio do report de erros -->

<% if @cliente.errors.any? %>
=======
<%= form_for(@cliente) do |f| %>
  <% if @cliente.errors.any? %>
>>>>>>> ad10758ddfdbf1227205791189757be3232ce289
    <div id="error_explanation">
      <h2><%= pluralize(@cliente.errors.count, "error") %> prohibited this cliente from being saved:</h2>

      <ul>
      <% @cliente.errors.full_messages.each do |message| %>
<<<<<<< HEAD

        <li><%= message %></li>

=======
        <li><%= message %></li>
>>>>>>> ad10758ddfdbf1227205791189757be3232ce289
      <% end %>
      </ul>
    </div>
  <% end %>
<<<<<<< HEAD
  <!-- Fim do Report de erros -->

  <!-- Inicio barra lateral -->
<div class="page-content">
        <div class="flex-grid no-responsive-future" style="height: 100%;">
            <div class="row" style="height: 100%">
                <div class="cell size-x200" id="cell-sidebar" style="background-color: #71b1d1; height: 100%">
                    <ul class="sidebar">
                        <li id="clientgrid" class="active" ><a>
                            <span class="mif-apps icon"></span>
                            <span class="title">Listar Clientes</span>
                            
                        </a></li>
                        <li id="calo" ><a >
                            <span class="mif-vpn-publ icon"></span>
                            <span class="title">Locais de Atendimento</span>
                            
                        </a></li>
                 
                    </ul>
                </div>

 <!-- Fim de Barra Lateral -->
  <!-- Conteudo da Página -->
<div id="inserthere"> </div>
  <div class="cell auto-size padding20 bg-white" id="cli">
                    <h1 class="text-light"> Painel de Clientes </h1>
                    <hr class="thin bg-grayLighter">
                    <br />
                    <br />
                    <br /> 
                    <button class="button primary" id="add" ><span class="mif-plus"></span> Novo Cliente</button>
         
                    <hr class="thin bg-grayLighter" > 

                   
                    <table class="dataTable border bordered" data-role="datatable" data-auto-width="false">

                        <thead>
                        <tr>
                            
                            <td class="sortable-column sort-asc" style="width: 10px">ID</td>
                          <td class="sortable-column" style="width: 60px">Nome:</td>
                           
                            <td class="sortable-column" style="width: 45px">Email:</td>
                            <td style="width: 45px">Telefone:</td>
                            <td style="width: 5px">Ações:</td>
                        </tr>
                        </thead>

                        <tbody>
                           <% @clientes.each do |cliente| %>
                           
                        <tr>
                            <td><%= cliente.id %></td>
                            <td><%= cliente.name %></td>
 <td><%= cliente.email %></td>
 <td><%= cliente.telefone %></td>
  <td> <%= link_to 'Alterar', edit_cliente_path(cliente) , class: 'm-btn green icn-only' %> <%= link_to 'Excluir', cliente, method: :delete, data: { confirm: 'Are you sure?' }, class: 'm-btn red icn-only'  %>  </td>
                            
                          
                           
                        </tr>
                        
                        <% end %>
                        </tbody>
                    </table>
                    
                </div>
            </div>
        </div>
    </div>


<!--  Conteudo Local -->

  <div class="cell auto-size padding20 bg-white" id="local">
                    <h1 class="text-light"> Locais de Atendimento </h1>
                    <hr class="thin bg-grayLighter">
                    <br />
                    <br />
                    <br /> 
                    <button class="button primary" id="addlocal" ><span class="mif-plus"></span> Adicionar Local</button>
         
                    <hr class="thin bg-grayLighter" > 

                   
                    <table class="dataTable border bordered" data-role="datatable" data-auto-width="false">

                        <thead>
                      
                            <td class="sortable-column sort-asc" style="width: 10px">ID</td>
                           <td class="sortable-column" style="width: 45px">Cliente:</td>
                           
                            <td class="sortable-column" style="width: 45px">Logradouro:</td>
                            <td style="width: 45px">CEP:</td>
     <td style="width: 45px">Estado:</td>
     <td style="width: 45px">Cidade:</td>
     <td style="width: 45px">Distancia em KM:</td>
     <td style="width: 5px"> Ações: </td>
                        </tr>
                        </thead>

                        <tbody>
                           <% @locals.each do |local| %>
                           
                        <tr>
                          
                            <td><%= local.id %></td>
                            <td><%= local.cliente.name %></td>
 <td><%= local.logra %></td>
 <td><%= local.cep %></td>
 <td><%= local.uf %></td>
 <td><%= local.city %></td>
 <td><%= local.km %></td>
   <td> <%= link_to 'Alterar', edit_local_path(local) , class: 'm-btn green icn-only' %> <%= link_to 'Excluir', local, method: :delete, data: { confirm: 'Are you sure?' }, class: 'm-btn red icn-only'  %>  </td>
                            
                          
                           
                        </tr>
                        
                        <% end %>
                        </tbody>
                    </table>
                    
                </div>
            </div>
        </div>
    </div>

<!-- Final da  conteudo  de local -->



<!-- Inicio do Cad Cliente JS --> 

 <div class="cal-form padding20 block-shadow">
   
         <span class="m-btn blue-stripe">Cadastro de Cliente</span>  <button style="float: right;" id="fecharcad" class="button alert" onclick="pushMessage('alert')">Cancelar</button>
            <hr class="thin"/>
            <br />
             <%= nested_form_for @cliente do |f| %>
            <div class="input-control text full-size" data-role="input">
                <label for="user_login">Nome Cliente/Fantasia: </label>
                 <%= f.text_field :name, id: 'user-login', :required => true , placeholder: "Nome do Cliente"%>
               
            </div>
           
  <br />
  <br />
            <div class="input-control text full-size" data-role="input">
                <label for="user_login">Telefone:</label>  
                    <%= f.text_field :telefone, id: 'user-login', required: true, placeholder: "Telefone de Contato" %>
             
            </div>

  <br />
  <br />

<div class="input-control text full-size" data-role="input">
                <label for="user_login">Email:</label>
                
 <%= f.text_field :email, id: 'user_login', required: true, placeholder: "Endereço de Email" %>
             
            </div>
  <br />

  <br />

            <br />  

   <%= f.fields_for :locals do |ff| %> 


<%= ff.text_field :logra, placeholder: "Logradouro"  %>  
  <%= ff.text_field :cep, placeholder: "CEP"  %>  
      <%= ff.text_field :uf, placeholder: "Estado"  %> 
   <%= ff.text_field :city , placeholder: "Cidade" %> 
   <%= ff.text_field :km , placeholder: "Distância"%>
<br />
<%= ff.link_to_remove "X",class: 'm-btn red icn-only' %>


<% end %>


 

 <%= f.link_to_add "Adicionar Local", :locals, class: 'button success' %> <br>
<br>
  <div class="actions">
  <%= f.submit 'Cadastrar', class: 'm-btn blue' %>
  </div>
<% end %>
  </div>


</div>


<!-- Inicio Local cad--> 



<div class="calo-form padding20 block-shadow">
      <span class="m-btn blue-stripe">Adicionar Local de Atendimento</span>  <button style="float: right;" id="fecharcalo" class="button alert" onclick="pushMessage('alert')">Voltar</button>
       
            <hr class="thin"/>
            <br />
             <%= form_for(@local) do |f| %>
            <div class="input-control text full-size" data-role="input">
                <label for="user_login">Cliente: </label>
                 
  <%= f.collection_select(:cliente_id, Cliente.all, :id, :name, prompt: "Selecionar Cliente", id: 'user-login') %>
                
            </div>
           
  <br />
  <br />
            <div class="input-control text full-size" data-role="input">
                <label for="user_login">Logradouro:</label>  
               
                  <%= f.text_field :logra, id: 'user-login', required: true, placeholder: "Endereço Completo" %>
            </div>

  <br />
  <br />
         <div class="input-control text full-size" data-role="input">
                <label for="user_login">CEP:</label>      
                <%= f.text_field :cep, id: 'user-login', required: true, placeholder: "CEP" %>
            </div>

  <br />
  <br />
      <div class="input-control text full-size" data-role="input">
                <label for="user_login">Estado:</label>      
                <%= f.text_field :uf, id: 'user-login', required: true, placeholder: "Estado/Região" %>
            </div>

  <br />
  <br />
   <div class="input-control text full-size" data-role="input">
                <label for="user_login">Cidade:</label>      
                <%= f.text_field :city, id: 'user-login', required: true, placeholder: "Cidade" %>
            </div>

  <br />
  <br />
   <div class="input-control text full-size" data-role="input">
                <label for="user_login">Distancia:</label>      
                <%= f.number_field :km, id: 'user-login', required: true, placeholder: "Distancia em KM" %>
            </div>

  <br />
  <br />
 
<br>
  <div class="actions">
  <%= f.submit 'Adicionar', class: 'm-btn blue' %>
  </div>

<% end %>
  </div>


</div>



 
=======

 <div class="form-group">
    <%= f.label :name, "Nome do Cliente" %><br>
    <%= f.text_field :name, class: 'namecli', :required => true %>
  </div>
 <div class="form-group">
    <%= f.label :telefone %><br>
    <%= f.text_field :telefone, :required => true %>
  </div>
  <div class="form-group">
    <%= f.label :celular %><br>
    <%= f.text_field :celular, :required => true %>
  </div>
 <div class="form-group">
    <%= f.label :email %><br>
    <%= f.text_field :email, class: 'namecli', :required => true %>
  </div>

   <%= f.fields_for :local do |ff| %>
<table> 
<tr>
<th>
    <%= ff.label :logra, "Logradouro" %><br></th>
<th>
     <%= ff.label :cep, "CEP" %></th>
<th>
     <%= ff.label :uf, "Estado" %></th>
<th>
    <%= ff.label :city, "Cidade" %></th>
<th>  <%= ff.label :km, "Distancia em KM" %> </th>
</tr>
<tbody class="tabela">
<tr class="linha" >
<td>  <%= ff.text_field :logra,  :required => true %>  </td>
    <td>  <%= ff.text_field :cep , :required => true %>  </td>
<td>      <%= ff.text_field :uf , :required => true %>  </td>
<td>   <%= ff.text_field :city , :required => true %>  </td>
<td>   <%= ff.text_field :km, :required => true %> </td>
<td><%= f.button 'Remover Local', type: 'button', class: 'remover' %></td>

</tr>
</tbody>
</table>

<% end %> 
  <div class="actions">
 <%= f.button 'Adicionar Local', type: 'button', class: 'adicionar' %> <br>
<br>
  <%= f.submit 'Enviar', class: 'btn btn-primary btn-lg' %>
  </div>
<% end %>

>>>>>>> ad10758ddfdbf1227205791189757be3232ce289

app/views/clientes/_forme.html.erb
<%= javascript_include_tag 'jquery.dataTables.min' %>


<!-- Inicio do clienterio de erros --> 
  <% if @cliente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cliente.errors.count, "error") %> prohibited this cliente from being saved:</h2>

      <ul>
      <% @cliente.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <!-- Fim do clienterio de erros --> 


  <!-- Inicio barra lateral -->
<div class="page-content">
        <div class="flex-grid no-responsive-future" style="height: 100%;">
            <div class="row" style="height: 100%">
                <div class="cell size-x200" id="cell-sidebar" style="background-color: #71b1d1; height: 100%">
                    <ul class="sidebar">
                        <li id="clientegrid" class="active" ><a href="/cliente">
                            <span class="mif-apps icon"></span>
                            <span class="title">Listar Clientes</span>
                            
                        </a></li>
  <li id="clientegridfin" ><a href="/cliente">
                            <span class="mif-apps icon"></span>
                            <span class="title">Locais de Atendimento </span>
                            
                        </a></li>
                       
                 
                    </ul>
                </div>

 <!-- Fim de Barra Lateral -->


 <!-- Conteudo da Página -->


<!-- Inicio do cadastro de relatórios --> 



 <div class="cell auto-size padding20 bg-white" id="cli">
    
  <div class="cadedit-form padding20 block-shadow">
   
         <span class="m-btn blue-stripe">Atualizar Dados Cadastrais</span> <a href="/cliente"> <button style="float: right;" id="fecharcad" class="button alert" onclick="pushMessage('alert')">Cancelar</button> </a>
            <hr class="thin"/>
            <br />
             <%= nested_form_for @cliente do |f| %>
            <div class="input-control text full-size" data-role="input">
                <label for="user_login">Nome Cliente/Fantasia: </label>
                 <%= f.text_field :name, id: 'user-login', :required => true , placeholder: "Nome do Cliente"%>
                
            </div>
           
  <br />
  <br />
            <div class="input-control text full-size" data-role="input">
                <label for="user_login">Telefone:</label>  
                    <%= f.text_field :telefone, id: 'user-login', required: true, placeholder: "Telefone de Contato" %>
             
            </div>

  <br />
  <br />

<div class="input-control text full-size" data-role="input">
                <label for="user_login">Email:</label>
                
 <%= f.text_field :email, id: 'user_login', required: true, placeholder: "Endereço de Email" %>
             
            </div>
  <br />

  <br />

            <br />  

   <%= f.fields_for :locals do |ff| %> 


<%= ff.text_field :logra, placeholder: "Logradouro"  %>  
  <%= ff.text_field :cep, placeholder: "CEP"  %>  
      <%= ff.text_field :uf, placeholder: "Estado"  %> 
   <%= ff.text_field :city , placeholder: "Cidade" %> 
   <%= ff.text_field :km , placeholder: "Distância"%>
<br />
<%= ff.link_to_remove "X",class: 'm-btn red icn-only' %>


<% end %>


 

 <%= f.link_to_add "Adicionar Local", :locals, class: 'button success' %> <br>
<br><br>
  <div class="actions">
  <%= f.submit 'Atualizar', class: 'm-btn blue' %>
  </div>
<% end %>



</div>
</div>
</div>

app/views/clientes/_forml.html.erb
<%= form_for(@local) do |f| %>
  <% if @local.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@local.errors.count, "error") %> prohibited this local from being saved:</h2>

      <ul>
      <% @local.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cliente_id %><br>
    <%= f.collection_select(:cliente_id, Cliente.all, :id, :name, prompt: true) %>
  </div>
  <div class="field">
    <%= f.label :logra %><br>
    <%= f.text_field :logra %>
  </div>
  <div class="field">
    <%= f.label :cep %><br>
    <%= f.text_field :cep %>
  </div>
  <div class="field">
    <%= f.label :uf %><br>
    <%= f.text_field :uf %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :km %><br>
    <%= f.number_field :km %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clientes/edit.html.erb
<<<<<<< HEAD

<%= render 'forme' %>



=======
<h1>Editing Cliente</h1>

<%= render 'form' %>

<%= link_to 'Show', @cliente %> |
<%= link_to 'Back', clientes_path %>
>>>>>>> ad10758ddfdbf1227205791189757be3232ce289

app/views/clientes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Clientes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Telefone</th>
      <th>Celular</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clientes.each do |cliente| %>
      <tr>
        <td><%= cliente.name %></td>
        <td><%= cliente.telefone %></td>
        <td><%= cliente.celular %></td>
        <td><%= cliente.email %></td>
        <td><%= link_to 'Show', cliente %></td>
        <td><%= link_to 'Edit', edit_cliente_path(cliente) %></td>
        <td><%= link_to 'Destroy', cliente, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cliente', new_cliente_path %>

app/views/clientes/new.html.erb
<<<<<<< HEAD

=======
<h1>Cadastro de Cliente</h1>
>>>>>>> ad10758ddfdbf1227205791189757be3232ce289

<%= render 'form' %>

<br>

<<<<<<< HEAD
=======

<%= link_to 'Back', clientes_path %>
>>>>>>> ad10758ddfdbf1227205791189757be3232ce289

app/views/clientes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @cliente.name %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @cliente.telefone %>
</p>

<p>
  <strong>Celular:</strong>
  <%= @cliente.celular %>
</p>

<p>
  <strong>Email:</strong>
  <%= @cliente.email %>
</p>


<%= link_to 'Adicionar Local', new_local_path(@local) %> |
<%= link_to 'Edit', edit_cliente_path(@cliente) %> |
<%= link_to 'Back', clientes_path %>