config/routes.rb
Rails.application.routes.draw do

<<<<<<< HEAD
  resources :tasks
  resources :relatos
  resources :conditionals
  resources :projetos
  resources :locals
  resources :clientes
  resources :reltasks
  resources :users, only: [:new, :create, :update, :destroy] do
=======
  resources :relatos
  resources :conditionals
  resources :tasks
  resources :projetos
  resources :locals
  resources :clientes
  resources :users, only: [:new, :create] do
>>>>>>> ad10758ddfdbf1227205791189757be3232ce289
    member do
      get :activate
    end
  end

  resources :reset_passwords, only: [:new, :create, :update, :edit]

  resources :sessions, only: [:new, :create, :destroy]

  get '/consultor', to: 'users#new', as: :sign_up
get '/cliente', to: 'clientes#new', as: :clienta
<<<<<<< HEAD
get '/projetos/new', to: 'projetos#new', as: :projetopo
=======
get '/projetos', to: 'projetos#index', as: :projete
>>>>>>> ad10758ddfdbf1227205791189757be3232ce289
get '/atividades', to: 'tasks#new', as: :taski
get '/relatorio', to: 'relatos#new', as: :relatoss
get '/condicional', to: 'conditionals#new', as: :condit
get '/local', to: 'locals#new', as: :loca

  get '/log_in', to: 'sessions#new', as: :log_in
  delete '/log_out', to: 'sessions#destroy', as: :log_out

<<<<<<< HEAD
=======
  get '/secret', to: 'pages#index', as: :secret
>>>>>>> ad10758ddfdbf1227205791189757be3232ce289

  root to: 'sessions#new'

end

app/models/projeto.rb
class Projeto < ActiveRecord::Base
has_many :clientes
belongs_to :user
belongs_to :cliente
has_many :tasks
belongs_to :task
belongs_to :page
has_many :relatos
<<<<<<< HEAD
has_many :reltasks
belongs_to :reltask
=======
>>>>>>> ad10758ddfdbf1227205791189757be3232ce289
accepts_nested_attributes_for :tasks, :allow_destroy => true
end

app/controllers/projetos_controller.rb
class ProjetosController < ApplicationController
  before_action :set_projeto, only: [:show, :edit, :update, :destroy]

  # GET /projetos
  # GET /projetos.json
  def index
    @projetos = Projeto.all
  end

  # GET /projetos/1
  # GET /projetos/1.json
  def show
<<<<<<< HEAD
@tasks = @projeto.tasks
=======
>>>>>>> ad10758ddfdbf1227205791189757be3232ce289
  end

  # GET /projetos/new
  def new
    @projeto = Projeto.new
<<<<<<< HEAD
     @projetos = Projeto.all
      @conditional = Conditional.new
 @conditionals = Conditional.all


=======
>>>>>>> ad10758ddfdbf1227205791189757be3232ce289
  end

  # GET /projetos/1/edit
  def edit
<<<<<<< HEAD
  @projetos = Projeto.all
  @projeto1 = Projeto.find(params[:id])


=======
>>>>>>> ad10758ddfdbf1227205791189757be3232ce289
  end

  # POST /projetos
  # POST /projetos.json
  def create
    @projeto = Projeto.new(projeto_params)

    respond_to do |format|
      if @projeto.save
<<<<<<< HEAD
        format.html { redirect_to projetopo_path, notice: 'Projeto criado com sucesso! Agora adicione uma Atividade para este projeto!' }
=======
        format.html { redirect_to taski_path, notice: 'Projeto criado com sucesso! Agora adicione uma Atividade para este projeto!' }
>>>>>>> ad10758ddfdbf1227205791189757be3232ce289
        format.json { render :show, status: :created, location: @projeto }
      else
        format.html { render :new }
        format.json { render json: @projeto.errors, status: :unprocessable_entity }
      end
    end
<<<<<<< HEAD

=======
>>>>>>> ad10758ddfdbf1227205791189757be3232ce289
  end

  # PATCH/PUT /projetos/1
  # PATCH/PUT /projetos/1.json
  def update
    respond_to do |format|
      if @projeto.update(projeto_params)
<<<<<<< HEAD
        format.html { redirect_to projetopo_path, notice: 'Projeto was successfully updated.' }
=======
        format.html { redirect_to @projeto, notice: 'Projeto was successfully updated.' }
>>>>>>> ad10758ddfdbf1227205791189757be3232ce289
        format.json { render :show, status: :ok, location: @projeto }
      else
        format.html { render :edit }
        format.json { render json: @projeto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projetos/1
  # DELETE /projetos/1.json
  def destroy
    @projeto.destroy
    respond_to do |format|
      format.html { redirect_to projetos_url, notice: 'Projeto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_projeto
      @projeto = Projeto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def projeto_params
<<<<<<< HEAD
      params.require(:projeto).permit(:id, :cliente_id, :name, :descr, :typo, :user_id, :dateini, :datefin, :status, :tasks_attributes => [:projeto_id, :raiz, :descr, :tempo, :typo, :id,  :parent_id])
    end

=======
      params.require(:projeto).permit(:cliente_id, :name, :descr, :typo, :user_id, :dateini, :datefin, :status)
    end
>>>>>>> ad10758ddfdbf1227205791189757be3232ce289
end

app/helpers/projetos_helper.rb
module ProjetosHelper
<<<<<<< HEAD


=======
>>>>>>> ad10758ddfdbf1227205791189757be3232ce289
end

app/views/projetos/_form.html.erb
<<<<<<< HEAD
<%= javascript_include_tag 'jquery.dataTables.min' %>
<!-- Inicio do report de erros -->
<% if @projeto.errors.any? %>
=======
<%= form_for(@projeto) do |f| %>
  <% if @projeto.errors.any? %>
>>>>>>> ad10758ddfdbf1227205791189757be3232ce289
    <div id="error_explanation">
      <h2><%= pluralize(@projeto.errors.count, "error") %> prohibited this projeto from being saved:</h2>

      <ul>
      <% @projeto.errors.full_messages.each do |message| %>
<<<<<<< HEAD

        <li><%= message %></li>

=======
        <li><%= message %></li>
>>>>>>> ad10758ddfdbf1227205791189757be3232ce289
      <% end %>
      </ul>
    </div>
  <% end %>
<<<<<<< HEAD
  <!-- fim do report de erros -->
<!-- Inicio barra lateral -->
<div class="page-content">
        <div class="flex-grid no-responsive-future" style="height: 100%;">
            <div class="row" style="height: 100%">
                <div class="cell size-x200" id="cell-sidebar" style="background-color: #71b1d1; height: 100%">
                    <ul class="sidebar">
                        <li id="projetogrid" class="active" ><a>
                            <span class="mif-apps icon"></span>
                            <span class="title">Projetos</span>
                            
                        </a></li>
                      
                        <li id="showcoc"><a>
                            <span class="mif-database icon"></span>
                            <span class="title">Condicionais</span>
                            
                        </a></li>
                      
                    </ul>
                </div>

 <!-- Fim de Barra Lateral -->

 <div id="projethere"> </div>
 <!-- Conteudo da Página -->

  <div class="cell auto-size padding20 bg-white" id="showproj1">
                    <h1 class="text-light"> Painel de Projetos</h1>
                    <hr class="thin bg-grayLighter">
                    <br />
                    <br />
                    <br /> 
                    <button class="button primary" id="addproj" ><span class="mif-plus"></span> Novo Projeto</button>
         
                    <hr class="thin bg-grayLighter" > 

                   
                   
                    <table class="dataTable border bordered" data-role="datatable" data-auto-width="false">

                        <thead>
                        <tr>
                            
                            <td class="sortable-column sort-asc" style="width: 100px">ID</td>
                            <td class="sortable-column" style="width: 45px">Cliente:</td>
                             <td class="sortable-column" style="width: 45px">Nome do Projeto:</td>
                              <td class="sortable-column" style="width: 70px">Descrição:</td>
                               <td class="sortable-column" style="width: 45px">Tipo:</td>
                                <td class="sortable-column" style="width: 45px">Gerente:</td>
                                 <td class="sortable-column" style="width: 45px">Data Inicial:</td>
                            <td class="sortable-column" style="width: 45px">Data Final:</td>
                                <td style="width: 5px">Ações:</td>

                        </tr>
                        </thead>

                        <tbody>
                           <% @projetos.each do |projeto| %>
                           
                        <tr>
                           
                                            <td><%= projeto.id %></td>
                            <td><%= projeto.cliente.name %></td>
                             <td><%= projeto.name %></td>
                               <td><%= projeto.descr %></td>
                                 <td><%= projeto.typo %></td>
                                   <td><%= projeto.user.name %></td>
                                     <td><%= projeto.dateini %></td>
                                       <td><%= projeto.datefin %></td>
                                         <td> <%= link_to 'Adicionar Atividade', edit_projeto_path(projeto) , class: 'm-btn green icn-only' %> <%= link_to 'Excluir', projeto, method: :delete, data: { confirm: 'Are you sure?' }, class: 'm-btn red icn-only'  %>  </td>
                            
                          
                           
                        </tr>
                        
                        <% end %>
                        </tbody>
                    </table>
                    
                </div>
            </div>
        </div>
    </div>


<!--  Fim do Conteudo MAIN -->


<!--  Inicio Cad Projeto-->

 <div id="cadproj" class="cap-form padding20 block-shadow">
<span class="m-btn green-stripe">Cadastrar Projeto</span><button style="float: right;" id="fecharcap" class="button alert" onclick="pushMessage('alert')">Cancelar</button>
            <hr class="thin"/>
            <br />
<%= form_for(@projeto) do |f| %>
    		<div class="input-control text full-size" data-role="input">
               	   <label for="user_login">Cliente: </label>
     			<%= f.collection_select(:cliente_id, Cliente.all, :id, :name, prompt: "Selecionar", :required => true) %>
  		</div>
 <br />
  <br />
<div class="input-control text full-size" data-role="input">
    <label for="user_login">Apelido do Projeto:</label>  
    <%= f.text_field :name, :required => true, id: 'user-login' %>
  </div>
 <br />
  <br />
 <div class="input-control text full-size" data-role="input">
    <label for="user_login">Descrição do Projeto:</label>  
    <%= f.text_area(:descr, :required => true, :size => 5) %>
  </div>
 <br />
  <br />
 <br />
  <br />
 <br />
  <br />
  <div class="input-control text full-size" data-role="input">
     <label for="user_login">Tipo:</label>  
    <%= f.select("typo", {"Avulso" => "Avulso", "Padrão" => "Padrao"}, :required => true, id: 'user-login') %>
  </div>
 <br />
  <br />
 <div class="input-control text full-size" data-role="input">
   <label for="user_login">Gerente:</label>  
     <%= f.collection_select(:user_id, User.all, :id, :name, prompt: "Selecionar", :required => true, id: 'user-login') %>
  </div>
 <br />
  <br />
 <div class="calendar-cell year-cell align-center year" data-role="input">
     <label for="user_login">Data Inicio:</label>  
    <%= f.date_select :dateini, :required => true , id: 'user-login'%>
  </div>
 <br />
  <br />
 <div class="calendar-cell year-cell align-center year" data-role="input">
    <label for="user_login">Data Fim:</label>  
    <%= f.date_select :datefin, :required => true, id: 'user-login' %>
  </div>
 <br />
  <br />
 
  <div class="actions">
  <%= f.submit 'Cadastrar', class: 'm-btn blue' %>
  </div>
<% end %>

</div>




<!--  Inicio CaC Geral -->

 <div class="cell auto-size padding20 bg-white"  id="cacgeral" >
                    <h1 class="text-light"> Painel de Condicionais</h1>
                    <hr class="thin bg-grayLighter">
                    <br />
                    <br />
                    <br /> 
                    <button class="button primary" id="addcoc" ><span class="mif-plus"></span> Nova Condicional</button>
         
                    <hr class="thin bg-grayLighter" > 

                   
                   
                    <table class="dataTable border bordered" data-role="datatable" data-auto-width="false">

                        <thead>
                        <tr>
                           
                            <td class="sortable-column sort-asc" style="width: 100px">ID</td>
                             <td class="sortable-column" style="width: 45px">Projeto:</td>
                              <td class="sortable-column" style="width: 70px">Translado:</td>
                               <td class="sortable-column" style="width: 45px">Intervalo:</td>
                                <td class="sortable-column" style="width: 45px">Distancia:</td>
                                 <td class="sortable-column" style="width: 45px">Data:</td>
                                  <td class="sortable-column" style="width: 45px">Tempo:</td>
                            <td class="sortable-column" style="width: 45px">Comentários:</td>

                        </tr>
                        </thead>

                        <tbody>
                           <% @conditionals.each do |conditional| %>
                           
                        <tr>
                           
                                            <td><%= conditional.id %></td>
                           <td><%= conditional.projeto.name %></td>
        <td><%= conditional.transla %></td>
        <td><%= conditional.interval %></td>
        <td><%= conditional.km %></td>
        <td><%= conditional.data %></td>
        <td><%= conditional.time %></td>
        <td><%= conditional.why %></td>
                          
                       </tr>
                        
                        <% end %>
                        </tbody>
                    </table>
                    
                </div>
            </div>
        </div>
    </div>


<!--  Fim do Conteudo MAIN  CAC -->





<!--  Inicio Cad Condicional -->

 <div class="cac-form padding20 block-shadow">
<span class="m-btn red-stripe">Cadastrar Condicional</span><button style="float: right;" id="fecharcac" class="button alert" onclick="pushMessage('alert')">Cancelar</button>
            <hr class="thin"/>
            <br />
<%= form_for(@conditional) do |f| %>
<div class="input-control text full-size" data-role="input">
    <label for="user_login">Projeto: </label>
    <%= f.grouped_collection_select :projeto_id, Cliente.order(:name), :projetos, :name, :id, :name, include_blank: true, class: 'form-control' %>
  </div>
<br />
<br />


<label class="input-control checkbox"> Translado: </label>
    <%= f.check_box :transla %> 
<label class="input-control checkbox"> Intervalo: </label>
    <%= f.check_box :interval %> 

<br />
<br />
  <div class="input-control text full-size" data-role="input">
     <label for="user_login">Descrição:</label> 
<%= f.text_area(:why, :required => true, :size => 2) %>
  </div>
<br />
<br />
<br />
<br />
<br />
<br />

   <label for="user_login">Data:</label>
   <%= f.date_select :data, :required => true, class: 'input-control text' %>

 
<br />
<br />
<label for="user_login">Duração:</label>
    <%= f.time_select(:time) %>
<br />
<br />
<br />

  <div class="input-control text" data-role="input">
    <label for="user_login">Distancia em KM: </label>
    <%= f.number_field :km %>
  </div>



     

<br />
<br />
<br />
<br />
  

  <div class="actions">
  <%= f.submit 'Cadastrar', class: 'm-btn blue' %>
  </div>
<% end %>
</div>


<!-- Inicio do Task Geral --> 



<!--  Fim do Conteudo MAIN -->


</div>
=======

  <div class="field">
    <%= f.label :cliente_id %><br>
     <%= f.collection_select(:cliente_id, Cliente.all, :id, :name, prompt: "Selecionar", :required => true) %>
  </div>
  <div class="field">
    <%= f.label :name, "Nome do Projeto" %><br>
    <%= f.text_field :name, :required => true %>
  </div>
  <div class="field">
    <%= f.label :descr, "Descrição do Projeto" %><br>
    <%= f.text_field :descr, :required => true %>
  </div>
  <div class="field">
    <%= f.label :typo, "Tipo do Projeto" %><br>
    <%= f.select("typo", {"Avulso" => "Avulso", "Padrão" => "Padrao"}, :required => true) %>
  </div>
  <div class="field">
    <%= f.label :user_id, "Gerente do Projeto" %><br>
     <%= f.collection_select(:user_id, User.all, :id, :name, prompt: "Selecionar", :required => true) %>
  </div>
  <div class="field">
    <%= f.label :dateini, "Data de Inicio" %><br>
    <%= f.date_select :dateini, :required => true %>
  </div>
  <div class="field">
    <%= f.label :datefin, "Data de Finalização" %><br>
    <%= f.date_select :datefin, :required => true %>
  </div>
 
  <div class="actions">
   <%= f.submit 'Enviar', class: 'btn btn-primary btn-lg' %>
  </div>
<% end %>
>>>>>>> ad10758ddfdbf1227205791189757be3232ce289

app/views/projetos/_forme.html.erb
<%= javascript_include_tag 'jquery.dataTables.min' %>


<!-- Inicio do projetorio de erros --> 
  <% if @projeto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@projeto.errors.count, "error") %> prohibited this projeto from being saved:</h2>

      <ul>
      <% @projeto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <!-- Fim do projetorio de erros --> 


  <!-- Inicio barra lateral -->
<div class="page-content">
        <div class="flex-grid no-responsive-future" style="height: 100%;">
            <div class="row" style="height: 100%">
                <div class="cell size-x200" id="cell-sidebar" style="background-color: #71b1d1; height: 100%;">
                    <ul class="sidebar">
                        <li id="projetogrid" class="active" ><a href="/projeto/new">
                            <span class="mif-apps icon"></span>
                            <span class="title">Listar projetos</span>
                            
                        </a></li>

                       
                 
                    </ul>
                </div>

 <!-- Fim de Barra Lateral -->


 <!-- Conteudo da Página -->


<!-- Inicio do cadastro de projeto edit --> 


  <!--  Inicio Cad Projeto-->
 <div class="cell auto-size padding20 bg-white" id="cli">
    


 <div id="cadprojedit" class="cadprojedit-form padding20 block-shadow">
<span class="m-btn green-stripe">Gerenciar Projeto</span><a href="/projeto/new"><button style="float: right;" id="fecharcap" class="button alert" onclick="pushMessage('alert')">Cancelar</button></a>
            <hr class="thin"/>
            <br />

<table >

                        <thead>
                        <tr>
                            <td>Atividades do Projeto</td>
<td></td>
 
                         	
			      
                             
                        </tr>
                        </thead>
                        <tbody>
                                   
                          <% nested_set_options(Task.where(projeto_id: @projeto1.id)) { |i|  "#{i.id} #{'–' * i.level}  #{i.raiz} #{i.descr}" }.each do |raiz, id| %>
                        <tr>
                         
                           	<td><%= raiz %> </td>
				<td>
</td>
			            
 			</tr>
                        <% end %>
                        </tbody>
                    </table>
<%= nested_form_for @projeto do |f| %>

<div style="float: right;" width="20%" >
<table >

                        <thead>
                        <tr>
                            <td>Identificador</td>
                         	     <td>Descrição</td>
     <td>Carga Horária</td>

     <td>Tipo</td>
     <td>ID Pai</td>
			      
                             
                        </tr>
                        </thead>
<br>
                        <tbody>  


<%= f.fields_for :tasks do |ff| %>
   

<td>

 <%=  ff.number_field :raiz, :placeholder => "Identificador" %></td> <td> 
 <%=  ff.text_field :descr, :placeholder => "Descrição" %>  </td><td> 
   <%=  ff.number_field :tempo, :placeholder => "Carga Horária Estimada" %> </td><td>
   <label for="user_login">Tipo de Atividade:</label>
 <%= ff.select("typo", {"Analitica" => "Analitica", "Sintetica" => "Sintetica"}) %></td><td> 
<%= ff.number_field :parent_id , :placeholder => "ID Pai"  %>
</td><%= ff.hidden_field(:projeto_id, :value => @projeto.id) %>
			            
 			</tr>
                        <% end %>
                        </tbody>
                    </table>
</div> 

 <%= f.link_to_add "Adicionar Atividade", :tasks, class: 'button success' %> <br>

<div id="editproj1">
    		<div class="input-control text full-size" data-role="input">
               	   <label for="user_login">Cliente: </label>
     			<%= f.collection_select(:cliente_id, Cliente.all, :id, :name, prompt: "Selecionar") %>
  		</div>
 <br />
  <br />
<div class="input-control text full-size" data-role="input">
    <label for="user_login">Apelido do Projeto:</label>  
    <%= f.text_field :name, id: 'user-login' %>
  </div>
 <br />
  <br />
 <div class="input-control text full-size" data-role="input">
    <label for="user_login">Descrição do Projeto:</label>  
    <%= f.text_area(:descr, :size => 5) %>
  </div>
 <br />
  <br />
 <br />
  <br />
 <br />
  <br />
  <div class="input-control text full-size" data-role="input">
     <label for="user_login">Tipo:</label>  
    <%= f.select("typo", {"Avulso" => "Avulso", "Padrão" => "Padrao"}, id: 'user-login') %>
  </div>
 <br />
  <br />
 <div class="input-control text full-size" data-role="input">
   <label for="user_login">Gerente:</label>  
     <%= f.collection_select(:user_id, User.all, :id, :name, prompt: "Selecionar", id: 'user-login') %>
  </div>
 <br />
  <br />
 <div class="calendar-cell year-cell align-center year" data-role="input">
     <label for="user_login">Data Inicio:</label>  
    <%= f.date_select :dateini, id: 'user-login'%>
  </div>
 <br />
  <br />
 <div class="calendar-cell year-cell align-center year" data-role="input">
    <label for="user_login">Data Fim:</label>  
    <%= f.date_select :datefin, id: 'user-login' %>
  </div>
 <br />
  <br />
 </div>

  <div class="actions">
  <%= f.submit 'Cadastrar', class: 'm-btn blue' %>
  </div>
<% end %>

</div></div>

</div></div>

app/views/projetos/edit.html.erb
<<<<<<< HEAD

<%= render 'forme' %>

=======
<h1>Editar Projeto</h1>

<%= render 'form' %>

<%= link_to 'Visualizar', @projeto %> |
<%= link_to 'Voltar', projetos_path %>
>>>>>>> ad10758ddfdbf1227205791189757be3232ce289

app/views/projetos/index.html.erb
<%= stylesheet_link_tag    '/themes/default/style.min.css', media: 'all'%>
<%= javascript_include_tag '/jstree.min.js' %>
<p id="notice"><%= notice %></p>

<h1>Lista de Projetos</h1>

<table id="customers">
  <thead>
    <tr class="alt">
      <th>Cliente</th>
      <th>Nome do Projeto</th>
      <th>Descrição do Projeto</th>
      <th>Tipo de Projeto</th>
      <th>Gerente do Projeto</th>
      <th>Data de Inicio</th>
      <th>Data de Finalização</th>
      <th>Andamento</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projetos.each do |projeto| %>
      <tr class="alt">
        <td><%= projeto.cliente_id %></td>
        <td><%= projeto.name %></td>
        <td><%= projeto.descr %></td>
        <td><%= projeto.typo %></td>
        <td><%= projeto.user.name %></td>
        <td><%= projeto.dateini %></td>
        <td><%= projeto.datefin %></td>
        <td><%= projeto.status %></td>
        <td><%= link_to 'TreeView', projeto %></td>
        <td><%= link_to 'Editar', edit_projeto_path(projeto) %></td>
        <td><%= link_to 'Deletar', projeto, method: :delete, data: { confirm: 'Alerta: O projeto será excluído!' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Criar novo Projeto', new_projeto_path %>

app/views/projetos/new.html.erb
<<<<<<< HEAD


<%= render 'form' %>


=======
<h1>Cadastro de Projetos</h1>

<%= render 'form' %>

<%= link_to 'Lista de Projetos', projetos_path %>
>>>>>>> ad10758ddfdbf1227205791189757be3232ce289

app/views/projetos/show.html.erb
<<<<<<< HEAD
<%= stylesheet_link_tag    '/themes/default/style.min.css', media: 'all'%>
<%= javascript_include_tag '/jstree.min.js' %>



=======
>>>>>>> ad10758ddfdbf1227205791189757be3232ce289
<p id="notice"><%= notice %></p>

<p>
  <strong>Cliente:</strong>
  <%= @projeto.cliente.name %>
</p>

<p>
  <strong>Nome do Projeto:</strong>
  <%= @projeto.name %>
</p>

<p>
  <strong>Descrição do Projeto:</strong>
  <%= @projeto.descr %>
</p>

<p>
  <strong>Tipo do Projeto:</strong>
  <%= @projeto.typo %>
</p>

<p>
  <strong>Gerente do Projeto:</strong>
  <%= @projeto.user.name %>
</p>

<p>
  <strong>Data de Inicio:</strong>
  <%= @projeto.dateini %>
</p>

<p>
  <strong>Data de Finalização:</strong>
  <%= @projeto.datefin %>
</p>
<<<<<<< HEAD
<div id="jstree">
<table id="customers">
<% @tasks.each do |d| %>
<tr class="alt">
<th> Identificador </th>
<th> Raiz </th>
<th> Filho </th>
<th> Tipo da Atividade </th>
<th> Descrição da Atividade </th>
</tr>
<tbody>
<tr class="alt1">
<td class="id"><%= d.id %></td>
<td class="raiz"><%= d.seqpai %></td>
<td ><%= d.seq %></td>
<td><%= d.typo %></td>
<td><%= d.descr %></td>
</tr>
<% end %>
</div>

</p>
=======

<p>
  <strong>Andamento:</strong>
  <%= @projeto.status %>
</p>

<p>
  <strong>Andamento:</strong>
  <%= @task.id %>
</p>



>>>>>>> ad10758ddfdbf1227205791189757be3232ce289
<%= link_to 'Editar', edit_projeto_path(@projeto) %> |
<%= link_to 'Lista de Projetos', projetos_path %>