config/routes.rb
Rails.application.routes.draw do

<<<<<<< HEAD
  resources :tasks
  resources :relatos
  resources :conditionals
  resources :projetos
  resources :locals
  resources :clientes
  resources :reltasks
  resources :users, only: [:new, :create, :update, :destroy] do
=======
  resources :relatos
  resources :conditionals
  resources :tasks
  resources :projetos
  resources :locals
  resources :clientes
  resources :users, only: [:new, :create] do
>>>>>>> ad10758ddfdbf1227205791189757be3232ce289
    member do
      get :activate
    end
  end

  resources :reset_passwords, only: [:new, :create, :update, :edit]

  resources :sessions, only: [:new, :create, :destroy]

  get '/consultor', to: 'users#new', as: :sign_up
get '/cliente', to: 'clientes#new', as: :clienta
<<<<<<< HEAD
get '/projetos/new', to: 'projetos#new', as: :projetopo
=======
get '/projetos', to: 'projetos#index', as: :projete
>>>>>>> ad10758ddfdbf1227205791189757be3232ce289
get '/atividades', to: 'tasks#new', as: :taski
get '/relatorio', to: 'relatos#new', as: :relatoss
get '/condicional', to: 'conditionals#new', as: :condit
get '/local', to: 'locals#new', as: :loca

  get '/log_in', to: 'sessions#new', as: :log_in
  delete '/log_out', to: 'sessions#destroy', as: :log_out

<<<<<<< HEAD
=======
  get '/secret', to: 'pages#index', as: :secret
>>>>>>> ad10758ddfdbf1227205791189757be3232ce289

  root to: 'sessions#new'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities

    user ||= User.new # guest user (not logged in)
    if user.role =="admin"
      can :manage, :all end
    if user.role =="normal"
     can :manage, Relato, :active => true, :user_id => user.id
    end
  end
end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
belongs_to :page
<<<<<<< HEAD
=======
has_one :local
>>>>>>> ad10758ddfdbf1227205791189757be3232ce289
has_many :projetos
belongs_to :projeto
has_many :relatos
has_many :locals
<<<<<<< HEAD
belongs_to :local
has_many :tasks, :through => :projetos
belongs_to :task
has_many :pages
accepts_nested_attributes_for :locals, allow_destroy: true
=======
has_many :tasks, :through => :projetos
belongs_to :task
has_many :pages
 accepts_nested_attributes_for :local 
>>>>>>> ad10758ddfdbf1227205791189757be3232ce289
end

app/models/conditional.rb
class Conditional < ActiveRecord::Base
belongs_to :relato
belongs_to :projeto
end

app/models/local.rb
class Local < ActiveRecord::Base
belongs_to :cliente
<<<<<<< HEAD
has_many :clientes
=======
has_many :relatos


>>>>>>> ad10758ddfdbf1227205791189757be3232ce289
end

app/models/page.rb
class Page < ActiveRecord::Base
  include TheSortableTree::Scopes
has_many :projetos
has_many :clientes
has_many :tasks
has_many :users 
  # any code here
end

app/models/projeto.rb
class Projeto < ActiveRecord::Base
has_many :clientes
belongs_to :user
belongs_to :cliente
has_many :tasks
belongs_to :task
belongs_to :page
has_many :relatos
<<<<<<< HEAD
has_many :reltasks
belongs_to :reltask
=======
>>>>>>> ad10758ddfdbf1227205791189757be3232ce289
accepts_nested_attributes_for :tasks, :allow_destroy => true
end

app/models/relato.rb
class Relato < ActiveRecord::Base
<<<<<<< HEAD
geocoded_by :ip_address
=======
>>>>>>> ad10758ddfdbf1227205791189757be3232ce289
belongs_to :cliente
belongs_to :projeto
belongs_to :local
belongs_to :task
<<<<<<< HEAD
has_many :relatos
belongs_to :user
belongs_to :reltask
has_many :reltasks
has_many :users

accepts_nested_attributes_for :reltasks, allow_destroy: true
=======
  
>>>>>>> ad10758ddfdbf1227205791189757be3232ce289

end

app/models/reltask.rb
class Reltask < ActiveRecord::Base
geocoded_by :ip_address
  belongs_to :task
  belongs_to :relato
  belongs_to :user
has_many :projetos
belongs_to :projeto
has_many :relatos
end

app/models/task.rb
class Task < ActiveRecord::Base
<<<<<<< HEAD
acts_as_nested_set
accepts_nested_attributes_for :children

has_many :projetos
belongs_to :projeto

=======
belongs_to :relato
has_many :relatos
has_many :projetos, :dependent => :destroy
belongs_to :projeto
belongs_to :page
has_many :pages
belongs_to :cliente
has_many :clientes , :through => :projetos
accepts_nested_attributes_for :projetos, :allow_destroy => true
>>>>>>> ad10758ddfdbf1227205791189757be3232ce289
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                           :integer          not null, primary key
#  email                        :string           not null
#  crypted_password             :string
#  salt                         :string
#  name                         :string
#  created_at                   :datetime
#  updated_at                   :datetime
#  remember_me_token            :string
#  remember_me_token_expires_at :datetime
#  failed_logins_count          :integer          default("0")
#  lock_expires_at              :datetime
#  unlock_token                 :string
#

class User < ActiveRecord::Base

 ROLES = %w[admin normal]

has_many :projetos
has_many :clientes
has_many :relatos
has_many :tasks
has_many :conditionals
<<<<<<< HEAD
belongs_to :relato
=======
>>>>>>> ad10758ddfdbf1227205791189757be3232ce289
authenticates_with_sorcery!

  validates :password, length: { minimum: 3 }
  validates :password, confirmation: true
  validates :email, uniqueness: true, email_format: { message: 'has invalid format' }

  class << self
    def current_users
      where("#{sorcery_config.last_activity_at_attribute_name} IS NOT NULL") \
  .where("#{sorcery_config.last_logout_at_attribute_name} IS NULL
    OR #{sorcery_config.last_activity_at_attribute_name} > #{sorcery_config.last_logout_at_attribute_name}") \
  .where("#{sorcery_config.last_activity_at_attribute_name} > ? ", sorcery_config.activity_timeout.seconds.ago.utc.to_s(:db))
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  include TheSortableTreeController::Rebuild

  def manage
    @pages = Page.nested_set.select('id, title, content, parent_id').all
  end

  # any code here


 def index
@clientes = Cliente.all
end

  def find
  
@tasks = Task.where("projeto_id = ?", projeto.id)
@projetos = Projeto.where("cliente_id = ?", cliente.id)
@clientes = Cliente.all


def pages_params
      params.require(:page).permit(:cliente, :task, :projeto, :user)
    end
end
end

app/helpers/application_helper.rb
module ApplicationHelper
def link_to_remove_fields(name, f)
f.hidden_field(:_destroy) + link_to_function(name, "remove_fields(this)")
end
def link_to_add_fields(name, f, association, locals={})
new_object = f.object.class.reflect_on_association(association).klass.new
fields = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|
render(association.to_s.singularize + "_fields", :f => builder)
end
link_to_function(name, "add_fields(this, \"#{association}\", \"#{escape_javascript(fields)}\")", class: locals[:class])
end
<<<<<<< HEAD

def user_report
Relato.where(user_id: @user1.find_by_id(@users)).count
end


=======
>>>>>>> ad10758ddfdbf1227205791189757be3232ce289
end

app/helpers/clientes_helper.rb
module ClientesHelper
<<<<<<< HEAD

=======
>>>>>>> ad10758ddfdbf1227205791189757be3232ce289
end

app/helpers/conditionals_helper.rb
module ConditionalsHelper
end

app/helpers/javascript_helper.rb
module JavascriptHelper
end

app/helpers/locals_helper.rb
module LocalsHelper
end

app/helpers/projetos_helper.rb
module ProjetosHelper
<<<<<<< HEAD


=======
>>>>>>> ad10758ddfdbf1227205791189757be3232ce289
end

app/helpers/relatos_helper.rb
module RelatosHelper
end

app/helpers/reltask_helper.rb
module ReltaskHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
<<<<<<< HEAD
=======


>>>>>>> ad10758ddfdbf1227205791189757be3232ce289
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Gerenciamento de Projetos</title>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'application' %>
<<<<<<< HEAD
  <%= javascript_include_tag 'metro' %>
  <%= stylesheet_link_tag "style" %>
  <%= stylesheet_link_tag "button" %>
  <%= stylesheet_link_tag "metro" %>
 <%= stylesheet_link_tag "form" %>
 <%= stylesheet_link_tag "metro-icons" %>
  <%= csrf_meta_tags %>
</head>
<!--  Inicio do Header -->
<body class="bg-steel">
    <div class="app-bar fixed-top darcula" data-role="appbar">
        <a class="app-bar-element branding">Infinit</a>
        <span class="app-bar-divider"></span>
        <ul class="app-bar-menu"><% if can? :read, @Application %> 
            <li><%= link_to 'Cliente', clienta_path %></li>
            <li><%= link_to 'Projeto', projetopo_path %></li>
            <li><%= link_to 'Relatorio', relatoss_path %></li>
            <li><%= link_to 'Consultor', sign_up_path %></li>
            <% end %>
           
        </ul>

        <div class="app-bar-element place-right">      <% if current_user %>
            <span class="dropdown-toggle"><span class="mif-cog"></span> <%= current_user.name %></span> <% end %>
            <div class="app-bar-drop-container padding10 place-right no-margin-top block-shadow" data-role="dropdown" data-no-close="true" style="width: 220px">
               
                <ul class="unstyled-list">
                    <li><a href="" class="fg-white fg-hover-yellow">Perfil</a></li>
                    <li><%= link_to 'Sair', log_out_path, method: :delete, class: 'fg-white fg-hover-yellow' %></li>
                </ul>
            </div>
        </div>
    </div>
    <!-- Fim do Header -->

<div>
=======
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <%= link_to 'Entrar', root_path, class: 'navbar-brand' %>
    </div>
    <div id="navbar">
      <ul class="nav navbar-nav">
        <% if current_user %>
          
        <% else %>
        
          <li><%= link_to 'Entrar', log_in_path %></li>
        <% end %>
      </ul>
      <% if current_user %>
        <ul class="nav navbar-nav pull-right">
          <li><span><%= current_user.name %></span></li>
<% if can? :read, @Application %> 
     <li><%= link_to 'Consultor', sign_up_path %></li>
<li><%= link_to 'Cliente', clienta_path %></li>
<li><%= link_to 'Projeto', projete_path %></li>
<li><%= link_to 'Atividade', taski_path %></li>
<% end %>
<li><%= link_to 'Relatorio', relatoss_path %></li><% if can? :read, @Application %>
<li><%= link_to 'Local de Atendimento', loca_path %></li>
<li><%= link_to 'Condicional', condit_path %></li><% end %>
          <li><%= link_to 'Sair', log_out_path, method: :delete %></li>
        </ul>
      <% end %>
    </div>
  </div>
</nav>

<div class="container">
>>>>>>> ad10758ddfdbf1227205791189757be3232ce289
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>">
      <%= value %>
    </div>
  <% end %>

<<<<<<< HEAD
  <div >
=======
  <div class="col-sm-9">
>>>>>>> ad10758ddfdbf1227205791189757be3232ce289
    <%= yield %>
  </div>

</div>

<<<<<<< HEAD

=======
<div id="footer">
  <div class="container">
    <p class="text-muted">Sistema desenvolvido por InfinIT</p>
  </div>
</div>
>>>>>>> ad10758ddfdbf1227205791189757be3232ce289

</body>
</html>

app/views/shared/_current_users.html.erb
<div class="col-sm-3 well well-sm">
  <h3>Usuários Ativos:</h3>
  <ul>
    <% current_users.each do |user| %>
      <li><%= user.name %></li>
    <% end %>
  </ul>
</div>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div class="panel panel-danger">
    <div class="panel-heading">
      <h3 class="panel-title">The following errors were found while submitting the form:</h3>
    </div>

    <div class="panel-body">
      <ul>
        <% object.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>